### ISSUE TITLE
Support of nullable types

### ISSUE THREAD

**Issue by Basim108** [Basim108/sql-bulk-service-postgresql#24]
Now there is now support of nullable properties. It fails with 
System.NotSupportedException: Type mapping from type 'System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' is not supported
   at Hrimsoft.SqlBulk.PostgreSql.DataTypeExtensions.ToNpgsql(Type propertyType)
   at Hrimsoft.SqlBulk.PostgreSql.EntityProfile.HasProperty[TEntity,TProperty](String column, Expression`1 propertyExpression, Boolean isPartOfUniqueConstraint)

**Comment by Basim108** [comment]
Implemented in version 1.1.3
